env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  quotes: 1
  no-mixed-spaces-and-tabs: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-tabs: 0
  no-console: 0
  no-restricted-syntax: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  linebreak-style: ["error", "windows"]