name: GitHub Actions Demo

run-name: ${{ github.actor }} testing ${{ inputs.deploy_target }}🚀

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependances
        run: make install
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}